### ISSUE TITLE
Add 'skip' configuration option

### ISSUE THREAD

**Issue by ilgrosso** [HebiRobotics/sass-cli-maven-plugin#1]
Sometimes it is useful to just skip a Maven plugin's execution, hence this plugin might add a configuration item like as follows:

```xml
      <plugin>
        <groupId>us.hebi.sass</groupId>
        <artifactId>sass-cli-maven-plugin</artifactId>
        <configuration>
           ...
           <skip>${sass.skip}</skip>
        </configuration>
      </plugin>
```

as many other Maven plugins are doing.

**Comment by ennerf** [comment]
Good idea. I released 1.0.2 with `<skip>` and `${sass.skip}`
