### ISSUE TITLE
Plugin execution won't stop

### ISSUE THREAD

**Issue by Andrea-Burgio** [HebiRobotics/sass-cli-maven-plugin#5]
I'm using IntelliJ IDEA 2023.3.2 (Ultimate Edition) Build #IU-233.13135.103, built on December 20, 2023.
I have included the plugin in the following way:
````
<plugin>
    <groupId>us.hebi.sass</groupId>
    <artifactId>sass-cli-maven-plugin</artifactId>
    <version>1.0.3</version>
    <configuration>
        <sassVersion>1.69.7</sassVersion>
        <args>
            <arg>${project.basedir}/src/main/resources/static/scss:${project.basedir}/src/main/resources/static/css</arg>
            <arg>--no-source-map</arg>
        </args>
    </configuration>
    <executions>
        <execution>
            <id>sass-exec</id>
            <phase>generate-resources</phase>
            <goals>
                <goal>run</goal>
            </goals>
        </execution>
    </executions>
</plugin>
````
To start the plugin i run the mvn sass-cli:watch command. Everything works perfectly until i try to stop it by either clicking the 'stop' button on the toolbar:
<img width="439" alt="Screenshot 2024-01-16 003744" src="https://github.com/HebiRobotics/sass-cli-maven-plugin/assets/125252455/4a744497-8196-4140-8b31-83d2596c30f4">
or the stop button in the Run toolbar:
<img width="1208" alt="Screenshot 2024-01-16 004222" src="https://github.com/HebiRobotics/sass-cli-maven-plugin/assets/125252455/3c374e71-76a7-44ec-a910-eda888c60cf8">
When i try to stop it the execution of the plugin won't stop.

The only way I've found is to close the tab in the Run toolbar, or restart the IDE. When i try to close IntelliJ, it can't close normally, and it asks me to kill the process:
<img width="439" alt="Screenshot 2024-01-16 003744" src="https://github.com/HebiRobotics/sass-cli-maven-plugin/assets/125252455/9f007b02-b3a9-4dfc-b0f2-921a847ac7b5">

This happens only when i make a change to a scss file and save it. The file is compiled to css correctly, but then the problem i mentioned above occurs. If i start the plugin with the mvn sass-cli:watch command and stop it right after (without making any changes to my watched scss files), the plugin closes correctly.

**Comment by ennerf** [comment]
I have tried a few things like adding explicit ctrl+c handling, but nothing seems to make a difference. I think it might come down to differences of the IntelliJ console, and it looks like there is nothing we can do about it. Sorry.
